### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zhl111** [rainbowflesh/F-ckS-msung#1]
我不懂it，按照您的说明直接运行得到这样的错误提示：

chmod : 无法将“chmod”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正
确，然后再试一次。
所在位置 行:1 字符: 1
+ chmod +x ./stupidSoftware.list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (chmod:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

如何正确操作呢？谢谢

**Comment by rainbowflesh** [comment]
在 windows 上执行就直接复制 stupidSoftware.list.sh 里面的脚本 (从第二行开始), 粘贴在控制台里运行. 
## 确保你的 adb 配置了[环境变量](https://www.cnblogs.com/mian-1122/p/14889701.html), 可以直接输入 `adb` 执行操作.

###### 当然不配置环境变量也可以, 就把每一行的 `adb` 换成 adb 可执行文件的地址就行, 例如:
```shell
# 假设安装位置在 /home/rainbow/App/adb/platform-tools/adb.exe, 则替换并执行
/home/rainbow/App/adb/platform-tools/adb.exe shell pm uninstall --user 0 com.samsung.android.carlink
```
